---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: blocklisted
  description: Source is gone
  color: 000000
- name: bug
  description: Something not working
  color: d73a4a
- name: confirmed
  description: Vetted and cleaned up issue
  color: 61dd50
- name: deprecated:template
  description: Dummy temlate issue
  color: f9d0c4
- name: deprecated
  description: Dummy issue
  color: adb9a6
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: ignore:malware
  description: Not really a specific piece of malware
  color: 006b75
- name: ignore:submodule
  description: Not really a specific offensive or defensive tool
  color: ca3460
- name: ignore:tag:wltm
  description: Not really a specific piece of malware
  color: d93f0b
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: missing:classification
  description: This issue hasn't been classified
  color: b04f3a
- name: missing:malware
  description: This issue relates to a piece of malware for which we do not have a sample
  color: f53fbf
- name: missing:submodule
  description: This issue relates to a specific offensive or defensive tool for which we have not added the submodule
  color: fef2c0
- name: missing:tactics
  description: This issue is missing tactics
  color: #bfd4f2
- name: missing:tag:wltm
  description: Specific malware sample required
- name: new
  description: On initial submission
  color: fbca04
- name: question
  description: Further information is requested
  color: d876e3
- name: triage
  description: Automated analysis performed
  color: eeeeee
- name: wontfix
  description: This will not be worked on
  color: ffffff
